slam_toolbox:
  ros__parameters:
    # Plugin for SLAM Toolbox
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link  # Standard base frame
    scan_topic: /scan
    mode: mapping  # Options: mapping, localization
    
    # Use odometry from RF2O
    use_scan_matching: true
    use_scan_barycenter: true

    # Map and transforms
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 25.0  # Match your LSC lidar range
    minimum_time_interval: 0.5
    transform_publish_period: 0.02  # 50 Hz transform publishing
    tf_buffer_duration: 30.0

    # General Parameters
    stack_size_to_use: 40000000  # program needs a larger stack size to serialize large maps
    enable_interactive_mode: true
    
    # Correlation Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1  # Reduced for better tracking without odom
    minimum_travel_heading: 0.1   # Reduced rotation threshold (radians)
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 20.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349  # 0.2 degrees
    coarse_search_angle_offset: 0.349   # 20 degrees
    coarse_angle_resolution: 0.0349     # 2 degrees
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # Auto-start parameters for SLAM Toolbox
    autostart: true